export const API_ENDPOINTS = {
  catalogsL1: "/catalogs",
  catalogsL2: "/catalogs2",
  catalogsL3: "/catalogs3",
  chemicals: "/chemicals",
  singleChemical: "/singleChemical",
  chemicalsFilter: "/chemicalsFilter",
  getUtility: "/getUtility",
  getBanner: "/banner",
  getCompanyMission: "/companymission",
  getSeviceheading: "/seviceheading",
  allServices: "/service/all",
  getVision: "/vision",
  allClients: "/client/all",
  getTestimonial: "/testimonial/all",
  getArticles: "/artical/all",
  getSettings: "/settings",
  getAboutBanner: "/about-us",
  getAboutUsCard: "/about-us-cards",
  getTimeline: "/timeline/all",
  contactUs: "/contact-form",
  personnelBanner: "/teambanner",
  personnelCharacterized: "/p-characteristics",
  getTeamMember: "/team/all",
};
